<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Login as Anybody for Orchard Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2015, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Login as Anybody for Orchard Core: An Orchard Core module that allows administrator users to log in as any user.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Login-as-Anybody</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Login-as-Anybody</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18924" />
    <PackageReference Include="OrchardCore.Users" Version="3.0.0-preview-18924" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.6.1-alpha.4.osoe-925" />
  </ItemGroup>

</Project>
